locale: "en-US"
title: "SHAOWEN JIN"
url: "https://shaowenjin.github.io"
baseurl: ""
google_analytics_key: ""

description: "The Continuous Professional Development of SHAOWEN JIN"

author:
  name: "SHAOWEN JIN"
  email: "shaowen.jin@postgrad.manchester.ac.uk"
  twitter: ""

social:
  name: "SHAOWEN JIN"
  links:
    - "https://github.com/shaowenjin"

permalink: "pretty"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-sitemap"

webmaster_verifications:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""

social_icons:
  - "Facebook"
  - "Google Plus" 
  - "Instagram"
  - "LinkedIn"
  - "Pinterest"
  - "Tumblr"
  - "Twitter"
  - "YouTube"
  - "RSS"
