# basic messages
title: "My Continuous Professional Development Webpage"
description: "I'm a postgraduate student in University of Manchester."
baseurl: ""
url: "https://shaowenjin.github.io"

# theme
remote_theme: old-jekyll-templates/Strata-Jekyll-Theme

# author
author:
  name: "SHAOWEN JIN"

# link
header_pages:
  - README.md
